### PR TITLE
Fix kubernetes-manifests/kustomization.yaml empty components issue

### LINKED ISSUE #1435: "Error: json: unknown field \"components\"\n"
### Describe the bug 

Get errors when run `skaffold run`, follows this document https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/docs/development-guide.md
### To Reproduce 

do exactly the same as the document, using kind.

### Logs  

```
Starting test...
running [kubectl --context  kustomize /home/ubuntu/microservices-demo/kubernetes-manifests]
 - stdout: ""
 - stderr: "Error: json: unknown field \"components\"\n"
 - cause: exit status 1

```
### Screenshots 

image

### Environment 

OS: Ubuntu 20.04
Kubernetes distribution, version: kind v0.17.0 go1.19.2 linux/amd64

### PR DESCRIPTION
**Pull request by phamquiluan**
This fixes #1435.

### CODE REVIEW

File: hack/make-release-artifacts.sh [hunk 1]
```diff
@@ -92,6 +92,11 @@ mk_istio_manifests() {
 mk_kustomize_base() {
   for file_to_copy in ./kubernetes-manifests/*.yaml
   do
+    # Don't copy kustomization.yaml.
+    if [[ $file_to_copy == "./kubernetes-manifests/kustomization.yaml" ]]; then
+      continue
+    fi
+
```
Comment (NimJay) [inline hack/make-release-artifacts.sh:99]: I just added this change into `hack/make-release-artifacts.sh`.
Context: Today, when a new release of Online Boutique is created `kubernetes-manifests/kustomization.yaml` is copied over to `kustomize/base/kustomization.yaml`. This should not be the case since the two files are meant to look different.
For instance, `kustomize/base/kustomization.yaml` should *not* include:
```
# components:
```
or
```
# - loadgenerator.yaml # During development, the loadgenerator module inside skaffold.yaml will be used.
```

**Review by NimJay — APPROVED** [review]
@phamquiluan sorry for the delayed review.
And thank you for:
1. creating a clear GitHub issue
2. creating a pull-request to fix the issue

I have not reproduced the issue on my end, but I trust that your fix worked for you.
Plus, the fix won't negatively impact anyone else's user experience.

Approved!
