### PR TITLE
node 12 -> node 16, grpc -> grpc-js

### LINKED ISSUE #538: Possible memory leak in NodeJS / Python services
Uptime checks for the production deployment of OnlineBoutique have been failing once every few weeks. Looking at `kubectl events` timed with an uptime check failure -- 

```
38m         Warning   NodeSysctlChange   node/gke-online-boutique-mast-default-pool-65a22575-azeq   {"unmanaged": {"net.ipv4.tcp_fastopen_key": "004baa97-3c3b554d-9bbcccf8-870ced36"}}
43m         Warning   NodeSysctlChange   node/gke-online-boutique-mast-default-pool-65a22575-i6m8   {"unmanaged": {"net.ipv4.tcp_fastopen_key": "706b7d5f-9df4b412-e8eb875e-179c4765"}}
46m         Warning   NodeSysctlChange   node/gke-online-boutique-mast-default-pool-65a22575-jvwz   {"unmanaged": {"net.ipv4.tcp_fastopen_key": "a0f734c5-5c9a56e1-06aeb420-0010498e"}}
39m         Warning   OOMKilling         node/gke-online-boutique-mast-default-pool-65a22575-jvwz   Memory cgroup out of memory: Kill process 569290 (node) score 2181 or sacrifice child
Killed process 569290 (node) total-vm:1418236kB, anon-rss:121284kB, file-rss:33236kB, shmem-rss:0kB
39m         Warning   OOMKilling         node/gke-online-boutique-mast-default-pool-65a22575-jvwz   Memory cgroup out of memory: Kill process 2592522 (grpc_health_pro) score 1029 or sacrifice child
Killed process 2592530 (grpc_health_pro) total-vm:710956kB, anon-rss:1348kB, file-rss:7376kB, shmem-rss:0kB
```

It looks like memory requests are exceeding their limit. There seems to be plenty of allocatable memory across the prod GKE nodes 
Screen Shot 2021-05-03 at 1 55 56 PM

But as observed by @bourgeoisor, it seems that three of the workloads are using steadily increasing amounts of memory until the pods are killed by GKE. 

Currency and payment (NodeJS):

Screen Shot 2021-05-03 at 2 23 13 PM

Recommendation: (Python)  

Screen Shot 2021-05-03 at 2 24 16 PM

TODO - investigate possible memory leaks starting with the NodeJS services. Investigate why the services use an increasing amount of memory over time rather than a constant amount. Then investigate the Python services + see if other python services (emailservice, for instance) show the same behavior as recommendation service.

### PR DESCRIPTION
**Pull request by askmeegs**
I came across these upgrades while trying to fix #538 - our Node and grpc JS versions were out of date and/or deprecated. This turned out to not be the cause of the memory leak but we should probably still upgrade. 

## changelog 

1. Upgrades the node base images for currency and payment service from Node 12 to Node 16. (Node 12 [is no longer the active version of Node](https://nodejs.org/en/about/releases/) and will go out of maintenance in April 2022. 
2. Upgrades the grpc package used in currency and payment service from `grpc` to `grpc-js`. `grpc` [is deprecated](https://www.npmjs.com/package/grpc). See [Migrating to grpc-js](https://www.npmjs.com/package/@grpc/grpc-js) for the `bind-async` change you see in this PR.

### CODE REVIEW

File: src/currencyservice/server.js [hunk 1]
```diff
@@ -169,8 +168,15 @@ function main () {
...
-  server.bind(`0.0.0.0:${PORT}`, grpc.ServerCredentials.createInsecure());
-  server.start();
+
+  server.bindAsync(
+    `0.0.0.0:${PORT}`,
+    grpc.ServerCredentials.createInsecure(),
+    function() {
+    server.start();
+     logger.info("gRPC server started.")
+    }
```
Comment (Shabirmean) [inline src/currencyservice/server.js:178]: Can we format it to match how we have it in the paymentservice/server.js?
- Update log text to be similar
- Switch log and `server.start()`
- make sure the lines are properly indented
```suggestion
    function() {
        logger.info(`CurrencyService gRPC server started on port ${PORT}`);
        server.start();
    },
```

**Review by Shabirmean — CHANGES_REQUESTED** [review]
Thank you for the change. Left a comment!

File: src/paymentservice/package.json [hunk 2]
```diff
@@ -12,15 +12,15 @@
   "license": "ISC",
   "dependencies": {
     "@google-cloud/debug-agent": "5.1.3",
-    "@google-cloud/profiler": "4.1.1",
+    "@google-cloud/profiler": "4.1.5",
```
Comment (Shabirmean) [inline src/paymentservice/package.json:15]: This upgraded needed because of [this error](https://github.com/GoogleCloudPlatform/microservices-demo/runs/4299781584?check_suite_focus=true) in the CI pipeline

The [v3.0.0./node-v93-linux-x64-musl.tar.gz] artifact of `pprof-nodejs` is not anymore found in the [artifacts bucket](https://storage.googleapis.com/cloud-profiler)

**Comment by Shabirmean** [comment]
I have updated the PR with some minor improvements. The diff between the last commit from the author and all my commits can be viewed at this link:

https://github.com/GoogleCloudPlatform/microservices-demo/compare/96c1a7fcece273fe5044b6542fa732867d04edeb...e568cfd7552757c990258e5d1599e89789a309c9

File: src/paymentservice/package.json (hunk 2 above)
Comment (NimJay) [reply src/paymentservice/package.json:15]: Thanks for figuring this out!

File: src/paymentservice/server.js [hunk 3]
```diff
@@ -55,17 +55,25 @@ class HipsterShopServer {
     }
   }
 
-  static CheckHandler (call, callback) {
```
Comment (NimJay) [inline src/paymentservice/server.js:58]: Thought: I think we can avoid this type of noise in pull-requests in the future by adding linting and automation to maintain consistent code style across this repository. This is something Olivier and I have been exploring for our 2022 roadmap.

**Review by NimJay — APPROVED** [review]
I have tried `skaffold dev` and did a quick smoke test of my deployment (on my GKE cluster).
The changes also look good, and yes, Node.js 16 is the way to go today.
Approved! 

Thanks, @Shabirmean, for taking over this pull-request and tidying it up. 🙏

**Review by Shabirmean — APPROVED** [review]
