### PR TITLE
Turn off GCP integrations by default

### LINKED ISSUE #663: Multiple services crashing out of the box due to missing credentials (local cluster)
Once I applied the release/kubernetes-manifests.yaml to a local cluster (kind, running kubernetes 1.23.0) I notice that a few pods are crashing, with logs indicating that either "project ID not set" or "cannot initialize credentials".

In earlier versions of this demo app, it worked both locally and on GCP without having to configure anything (such as adjusting the environment variables), and that was one of the principles we wanted to keep per go/microservices-demo doc. I recommend restoring that behavior as it's useful to first-time users.

paymentservice (CrashLoopBackOff)
```
 kubectl logs -f paymentservice-54b7545694-6rjwv
(node:1) [changeLevelName_deprecation] Warning: The changeLevelName option is deprecated and will be removed in v7. Use levelKey instead.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) [changeLevelName_deprecation] Warning: The changeLevelName option is deprecated and will be removed in v7. Use levelKey instead.
{"severity":"info","time":1639616190938,"pid":1,"hostname":"paymentservice-54b7545694-6rjwv","name":"paymentservice-server","message":"PaymentService gRPC server started on port 50051","v":1}
/usr/src/app/node_modules/@google-cloud/profiler/build/src/index.js:120
        throw new Error('Project ID must be specified in the configuration');
              ^

Error: Project ID must be specified in the configuration
    at initConfigMetadata (/usr/src/app/node_modules/@google-cloud/profiler/build/src/index.js:120:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createProfiler (/usr/src/app/node_modules/@google-cloud/profiler/build/src/index.js:158:26)
    at async Object.start (/usr/src/app/node_modules/@google-cloud/profiler/build/src/index.js:182:22)
```

shippingservice (CrashLoopBackOff)

```
{"message":"Tracing enabled.","severity":"info","timestamp":"2021-12-16T00:57:44.94692172Z"}
{"message":"Profiling enabled.","severity":"info","timestamp":"2021-12-16T00:57:44.946979558Z"}
{"message":"jaeger initialization disabled.","severity":"info","timestamp":"2021-12-16T00:57:44.947065127Z"}
{"message":"Stats enabled.","severity":"info","timestamp":"2021-12-16T00:57:44.94706558Z"}
{"message":"Shipping Service listening on port :50051","severity":"info","timestamp":"2021-12-16T00:57:44.947360261Z"}
{"message":"failed to initialize Stackdriver exporter: stackdriver: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.","severity":"warning","timestamp":"2021-12-16T00:57:44.948239335Z"}
{"message":"sleeping 10s to retry initializing Stackdriver exporter","severity":"info","timestamp":"2021-12-16T00:57:44.948266195Z"}
{"message":"failed to start profiler: project ID must be specified in the configuration if running outside of GCP","severity":"warning","timestamp":"2021-12-16T00:57:44.948276815Z"}
{"message":"sleeping 10s to retry initializing Stackdriver profiler","severity":"info","timestamp":"2021-12-16T00:57:44.948283437Z"}
{"message":"failed to start profiler: project ID must be specified in the configuration if running outside of GCP","severity":"warning","timestamp":"2021-12-16T00:57:54.948410021Z"}
{"message":"sleeping 20s to retry initializing Stackdriver profiler","severity":"info","timestamp":"2021-12-16T00:57:54.948468961Z"}
{"message":"failed to initialize Stackdriver exporter: stackdriver: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.","severity":"warning","timestamp":"2021-12-16T00:57:54.948444596Z"}
{"message":"sleeping 20s to retry initializing Stackdriver exporter","severity":"info","timestamp":"2021-12-16T00:57:54.948480152Z"}
```

currencyservice (CrashLoopBackOff)

```
Profiler enabled.
Tracing enabled.
Debugger enabled.
{"severity":"info","time":1639616372847,"pid":1,"hostname":"currencyservice-68b9dd7dcb-nc4fh","name":"currencyservice-server","message":"Starting gRPC server on port 7000...","v":1}
(node:1) [changeLevelName_deprecation] Warning: The changeLevelName option is deprecated and will be removed in v7. Use levelKey instead.
(Use `node --trace-warnings ...` to show where the warning was created)
{"severity":"info","time":1639616372944,"pid":1,"hostname":"currencyservice-68b9dd7dcb-nc4fh","name":"currencyservice-server","message":"CurrencyService gRPC server started on port 7000","v":1}
/usr/src/app/node_modules/@google-cloud/profiler/build/src/index.js:120
        throw new Error('Project ID must be specified in the configuration');
              ^

Error: Project ID must be specified in the configuration
    at initConfigMetadata (/usr/src/app/node_modules/@google-cloud/profiler/build/src/index.js:120:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createProfiler (/usr/src/app/node_modules/@google-cloud/profiler/build/src/index.js:158:26)
    at async Object.start (/usr/src/app/node_modules/@google-cloud/profiler/build/src/index.js:182:22)
```

### PR DESCRIPTION
**Pull request by askmeegs**
### Background 

Turns off Google Cloud Monitoring, Tracing, Profiler, and Debugger for all services by default, to re-enable out of the box support for local clusters. 

### Fixes 

#663  

### Change Summary

1) Comments out `DISABLE_PROFILER=1` etc for all services, thus turning off GCP integrations by default 
2) Payments service, for some reason, didn't look at these env variables so none of the GCP integraitons were toggle-able. fixed that. 

### Testing Procedure

1. Create a local cluster (kind or minikube)
2. Have a project ID ready to go, `PROJECT_ID` env field set (for GCR)
3. `skaffold run --default-repo=gcr.io/$PROJECT_ID/onlineboutique` this will test the `kubernetes-manifests`, *not* `release/` on a local cluster. that's what you want. 
4. Verify that all pods start up without errors.

### CODE REVIEW

**Review by ahrarmonsur — APPROVED** [review]
Code looks good. I manually tested, following the guidelines, and was able to get the app stood up without errors. The logs posted the following, as the expected default behaviour:
```
Profiler disabled.
Tracing disabled.
Debugger disabled.
```

LGTM!

File: src/paymentservice/index.js [hunk 1]
```diff
@@ -16,19 +16,43 @@
...
-require('@google-cloud/trace-agent').start();
-require('@google-cloud/debug-agent').start({
-  serviceContext: {
-    service: 'paymentservice',
-    version: 'VERSION'
-  }
-});
+
+if(process.env.DISABLE_PROFILER) {
+  console.log("Profiler disabled.")
```
Comment (NimJay) [inline src/paymentservice/index.js:21]: Suggestion: Should we use `pino` instead of `console.log`?
* I'm guessing we copied this newly added code from [`/src/currencyservice/server.js`](https://github.com/GoogleCloudPlatform/microservices-demo/blob/2554fe8b154750e17fa8a5a3bb7dd402489d13a7/src/currencyservice/server.js).
* We could define a `pino` logger at the top of `src/paymentservice/index.js` (after `'use strict';`) and use that instead:
```
const logger = pino({
  name: 'paymentservice-server',
  messageKey: 'message',
  changeLevelName: 'severity',
  useLevelLabels: true
});
```
* We could also refactor [`/src/currencyservice/server.js`](https://github.com/GoogleCloudPlatform/microservices-demo/blob/2554fe8b154750e17fa8a5a3bb7dd402489d13a7/src/currencyservice/server.js) in a similar fashion.
  * It looks like the use of `pino` was introduced in [#66](https://github.com/GoogleCloudPlatform/microservices-demo/pull/66). 
  * And the console.log statements were later introduced in [#293](https://github.com/GoogleCloudPlatform/microservices-demo/pull/293).
  * So the use of `console.log` _could_ _possibly_ be intentional?

File: kubernetes-manifests/adservice.yaml [hunk 2]
```diff
@@ -35,10 +35,10 @@ spec:
...
         - name: PORT
           value: "9555"
-        # - name: DISABLE_STATS
-        #   value: "1"
-        # - name: DISABLE_TRACING
-        #   value: "1"
+        - name: DISABLE_STATS
+          value: "1"
+        - name: DISABLE_TRACING
+          value: "1"
```
Comment (NimJay) [inline kubernetes-manifests/adservice.yaml:41]: Question: Do you know if disabling Cloud Tracing, etc. by default would require adding an extra step in some of the existing tutorials?
* For instance, could it break this [Exporting to BigQuery tutorial](https://cloud.google.com/trace/docs/trace-export-bigquery#hipstershop-query)? I can't really tell — because this tutorial is a bit vague.

**Review by NimJay — CHANGES_REQUESTED** [review]
Thanks for letting me review this before merging, @askmeegs!
I've left 2 comments.

File: src/paymentservice/index.js (hunk 1 above)
Comment (askmeegs) [reply src/paymentservice/index.js:21]: Yes I copied this from currencyservice - is this in scope for this PR, or can we add the `pino` logging in another PR?

File: kubernetes-manifests/adservice.yaml (hunk 2 above)
Comment (askmeegs) [reply kubernetes-manifests/adservice.yaml:41]: It's interesting because this tutorial doesn't have the user deploy the app. It just assumes they already have. 

I will update the readme to add a notice about how to re-enable GCP instrumentation, overriding the default.

File: src/paymentservice/index.js (hunk 1 above)
Comment (NimJay) [reply src/paymentservice/index.js:21]: Agreed. The `pino`-related work is outside the scope of this PR.
I've created an issue to track `pino`-related work: https://github.com/GoogleCloudPlatform/microservices-demo/issues/674.

**Review by NimJay — APPROVED** [review]
Thanks so much for doing this, @askmeegs!
Changes look good to me!
Ahrar has also done the appropriate testing.
Approved.

**Unrelated Note**
I realized that the code style (e.g., bracket style) varies across this repository. 
But again, this concern is definitely outside the scope of this pull-request.
Thus, I've created a separate GitHub issue about enforcing consistent coding style in JavaScript/Node.js service: https://github.com/GoogleCloudPlatform/microservices-demo/issues/675.
