### PR TITLE
[cartservice] Increases health check timeout

### LINKED ISSUE #74: cartservice: unhealthy signals from grpc
cartservice (@ 3b6d3864a0fa66495faa6b9803078710d1013398) restarts once about every 30 minutes and has a bunch of failed probe events.

```
Events:
  Type     Reason     Age                      From                                           Message
  ----     ------     ----                     ----                                           -------
  Warning  Unhealthy  39m (x13 over 3h33m)     kubelet, gke-istio-default-pool-d396f934-mvhs  Liveness probe failed: service unhealthy (responded with "NOT_SERVING")
  Warning  Unhealthy  39m (x12 over 3h33m)     kubelet, gke-istio-default-pool-d396f934-mvhs  Readiness probe failed: service unhealthy (responded with "NOT_SERVING")
  Warning  Unhealthy  21m (x83 over 4h16m)     kubelet, gke-istio-default-pool-d396f934-mvhs  Readiness probe failed: timeout: health rpc did not complete within 1s
  Warning  Unhealthy  6m22s (x103 over 4h16m)  kubelet, gke-istio-default-pool-d396f934-mvhs  Liveness probe failed: timeout: health rpc did not complete within 1s
```

most prominently the `timeout: health rpc did not complete within 1s` error from grpc_health_probe.

This requires some investigation as for why Check() can't complete within 1s.

### PR DESCRIPTION
**Pull request by askmeegs**
Closes #74 

**Problem**: CartService restarts repeatedly due to failed liveness and readiness probes (the redis PING completes, but it takes > 1 second). Isolated the problem to the .NET StackExchange/Redis client library -- unclear if it's a timeout or connection pool issue.

**Solution for now**:

1. Increase the timeout on both the liveness/readiness probes from 1 second to 5 seconds 
2. Re-use the existing cartservice redis client in the health check, rather than initialize a new client (this just adds more time) 
3. Upgrade the Redis .NET library to the [latest version](https://www.nuget.org/packages/StackExchange.Redis/)

### CODE REVIEW

File: src/cartservice/HealthImpl.cs [hunk 1]
```diff
@@ -14,11 +15,14 @@ internal class HealthImpl : HealthBase {
...
-            Console.WriteLine ("Checking CartService Health");
-
-            return Task.FromResult(new HealthCheckResponse {
+            var watch = StartNew();
+            var result = Task.FromResult(new HealthCheckResponse {
                 Status = dependency.Ping() ? HealthCheckResponse.Types.ServingStatus.Serving : HealthCheckResponse.Types.ServingStatus.NotServing
             });
+            watch.Stop();
+            var elapsedMs = watch.ElapsedMilliseconds;
+            Console.WriteLine ("✅ Health Check took " + elapsedMs + "ms");
```
Comment (ahmetb) [inline src/cartservice/HealthImpl.cs]: You might want to remove this if you added it just for debugging. I am not sure if it will generate a lot of logs.
